export class production{
  id: number;
  insplot: number;
  orderno: number;
  roundno: string;
  qty: number;
  plantcode: string;
  shift: string;
  itemcode: string;
  itemname: string;
  size: string;
  type: string;
  okqty: number;
  holdqty: number;
  buffingqty: number;
  rejectionqty: number;
  pitting: number;
  pinhole: number;
  patchmark: number;
  nickle: number;
  crburning: number;
  skipplating: number;
  dent: number;
  handmouldingrej: number;
  scratchmark: number;
  roughness:number;
  silver:number;
  mouldingrej:number;
  warpage:number;
  copperburning:number;
  whitemark:number;
  dotplastic:number;
  watermark:number;
  blister:number;
  jigdamage:number;
  otheR1:number;
  otheR2:number;
  otheR3:number;
  otheR4:number;
  mechfail:number;
  tooldef:number;
  others:number;
  shadevar:number;
  platingpeel:number;
  flowmark:number;
  chemicalmark:number;
  pstngdate:string;
}
